apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: rhdh-agent-sandbox
  description: Agent-friendly Developer Hub demo on OpenShift Developer Sandbox
  tags:
    - ai
    - mcp
    - lightspeed
    - demo
  annotations:
    backstage.io/techdocs-ref: url:https://github.com/maximilianoPizarro/rhdh-agent-sandbox/tree/main/files/techdocs/platform
    backstage.io/kubernetes-label-selector: "app.kubernetes.io/part-of=rhdh-agent-sandbox"
    backstage.io/kubernetes-namespace: __RELEASE_NAMESPACE__
spec:
  type: website
  lifecycle: experimental
  owner: group:default/developers
  system: agent-sandbox
