{{- if .Values.catalog.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rhdh-agent-sandbox.fullname" . }}-registered-catalog
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rhdh-agent-sandbox.labels" . | nindent 4 }}
    app.kubernetes.io/component: registered-catalog
data: {}
{{- end }}
